services:
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  fastapi:
    container_name: recipeservice-api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: recipeservice-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - DEBUG=true
    volumes:
      - ./:/recipeservice
    depends_on:
      - mongo
    restart: on-failure
volumes:
  mongo-data:
