services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: false
    links:
      - mongo
    networks:
      - mongo-compose-network

  fastapi:
    container_name: recipeservice-api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: recipeservice-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - DEBUG=true
    volumes:
      - ./:/recipeservice
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge