services:
  recipeservice-prod:
    container_name: recipeservice-prod
    image: recipeservice-prod
    profiles: [prod]
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - 8001:8001
    env_file:
      - .env_prod
    volumes:
      - ./:/recipeservice
    restart: on-failure

  mongo:
    image: mongo
    profiles: [dev]
    restart: always
    env_file: 
    - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network


  mongo-express:
    image: mongo-express
    profiles: [dev]
    ports:
      - 8080:8081
    env_file: 
    - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: false
    links:
      - mongo
    networks:
      - mongo-compose-network

  recipeservice-dev:
    container_name: recipeservice-dev
    image: recipeservice-dev
    profiles: [dev]
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file: 
    - .env
    ports:
      - "8001:8080"
    environment:
      - DEBUG=true
    volumes:
      - ./:/recipeservice
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge