name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Verification
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Creating .env
        run: |
          cat <<EOF > .env
          ME_CONFIG_MONGODB_URL=mongodb://root:admin@localhost:27017/
          MONGO_DB_NAME=db_name
          ME_CONFIG_MONGODB_ADMINUSERNAME=root
          ME_CONFIG_MONGODB_ADMINPASSWORD=admin
          MONGO_INITDB_ROOT_USERNAME=root
          MONGO_INITDB_ROOT_PASSWORD=admin
          EOF

      - name: Run docker compose
        run: docker compose --profile dev up -d --build

      - name: Wait building
        run: sleep 5

      - name: Test endpoint
        run: curl --fail http://localhost:8001/health/ 

      - name: Closing containers
        if: always()
        run: docker compose down
