name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          cat <<EOF > .env
          ME_CONFIG_MONGODB_URL=mongodb://root:admin@localhost:27017/
          ME_CONFIG_MONGODB_ADMINUSERNAME=root
          ME_CONFIG_MONGODB_ADMINPASSWORD=admin
          MONGO_INITDB_ROOT_USERNAME=root
          MONGO_INITDB_ROOT_PASSWORD=admin
          EOF

      - name: Run docker compose
        run: docker compose up -d --build

      - name: Wait building
        run: sleep 5

      - name: Run tests using pytest
        run: docker compose exec fastapi pytest tests/

      - name: Closing containers
        if: always()
        run: docker compose down
